# Generated by Django 6.0.3 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_phase3_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expected fee amount in EGP.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='Reference number from the payment provider.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='used',
            field=models.BooleanField(db_index=True, default=False, help_text='True after submitted to a payment gateway — prevents replay.'),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='actor',
            field=models.CharField(default='system', help_text='Who triggered this event.', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
