# Generated by Django 6.0.3 on 2026-03-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_alter_payment_amount_alter_payment_gateway_reference_and_more",
        ),
        ("payments", "0003_payment_processing_status_and_methods"),
    ]

    operations = []
