# Generated by Django 6.0.3 on 2026-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20260325_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this payment expires and becomes terminal.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing at Gateway'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='event_type',
            field=models.CharField(choices=[('initiated', 'Payment Initiated'), ('processing', 'Processing at Gateway'), ('success', 'Payment Confirmed'), ('failure', 'Payment Failed'), ('cancelled', 'Cancelled by Student/Admin'), ('webhook', 'Webhook Received'), ('refund', 'Refund Issued'), ('replay_blocked', 'Replay Attack Blocked'), ('expired', 'Payment Expired')], db_index=True, max_length=30),
        ),
    ]
