# Generated by Django 6.0.3 on 2026-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_expires_at_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentauditlog',
            name='event_type',
            field=models.CharField(choices=[('initiated', 'Payment Initiated'), ('processing', 'Processing at Gateway'), ('success', 'Payment Confirmed'), ('failure', 'Payment Failed'), ('cancelled', 'Cancelled by Student/Admin'), ('webhook', 'Webhook Received'), ('refund', 'Refund Issued'), ('invalid_webhook_signature', 'Invalid Webhook Signature'), ('malformed_webhook_payload', 'Malformed Webhook Payload'), ('duplicate_webhook_noop', 'Duplicate Webhook No-Op'), ('terminal_state_noop', 'Terminal State No-Op'), ('expired', 'Payment Expired')], db_index=True, max_length=30),
        ),
    ]
